In [0]:
import torch as t

In [2]:
t.__version__

'1.1.0'

In [0]:
t.Tensor??

In [4]:
a = t.Tensor(3, 4)
a

tensor([[1.1596e-35, 0.0000e+00, 3.7835e-44, 0.0000e+00],
        [       nan, 1.4153e-43, 1.3733e-14, 6.4069e+02],
        [4.3066e+21, 1.1824e+22, 4.3066e+21, 6.3828e+28]])

torch.Size 是 tuple对象 的子类，因此它支持tuple的所有操作，如`a.size()[0]`

---



In [5]:
print(a.size(0))
print(a.size()[0])

3
3


In [6]:
# 使用[0,1]均匀分布随机初始化数组
x = t.rand(3, 4)
y = t.rand(3, 4)
x, y

(tensor([[0.1566, 0.0594, 0.3029, 0.2390],
         [0.9658, 0.6840, 0.7074, 0.0034],
         [0.1957, 0.1443, 0.3377, 0.4644]]),
 tensor([[0.1460, 0.9676, 0.7460, 0.3093],
         [0.2367, 0.0599, 0.4462, 0.2872],
         [0.9349, 0.7484, 0.2394, 0.0174]]))

In [7]:
# 三种加法方式
print(x + y)

print(t.add(x, y))

result = t.rand(3, 4)
t.add(x, y, out=result)
result

tensor([[0.3026, 1.0269, 1.0489, 0.5483],
        [1.2025, 0.7439, 1.1536, 0.2906],
        [1.1307, 0.8926, 0.5771, 0.4818]])
tensor([[0.3026, 1.0269, 1.0489, 0.5483],
        [1.2025, 0.7439, 1.1536, 0.2906],
        [1.1307, 0.8926, 0.5771, 0.4818]])


tensor([[0.3026, 1.0269, 1.0489, 0.5483],
        [1.2025, 0.7439, 1.1536, 0.2906],
        [1.1307, 0.8926, 0.5771, 0.4818]])